### ISSUE TITLE
[DEFECT]- Failing to init API v1.0.5

### ISSUE THREAD

**Issue by masterfaka** [xivira/miai-api#1]
After a loong evening of head-scratching managed to make it build in a new Angular 15 project with the following config:
- package.json
```js
{
  "name": "my-investor-api",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/cdk": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/material": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "assert": "^2.0.0",
    "buffer": "^6.0.3",
    "crypto-browserify": "^3.12.0",
    "fs": "^0.0.1-security",
    "https-browserify": "^1.0.0",
    "miai-api": "^1.0.5",
    "os-browserify": "^0.3.0",
    "process": "^0.11.10",
    "rxjs": "~7.8.0",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "tslib": "^2.3.0",
    "url": "^0.11.0",
    "uuid": "^9.0.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^15.0.0",
    "@angular-devkit/build-angular": "^15.1.1",
    "@angular/cli": "~15.1.1",
    "@angular/compiler-cli": "^15.1.0",
    "@types/jasmine": "~4.3.0",
    "@types/uuid": "^9.0.0",
    "fs-web": "^1.0.1",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.4"
  }
}

```

- tsconfig.json
```js/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "paths" : {
      "crypto": ["./node_modules/crypto-browserify"],
      "stream": ["./node_modules/stream-browserify"],
      "assert": ["./node_modules/assert"],
      "http": ["./node_modules/stream-http"],
      "https": ["./node_modules/https-browserify"],
      "os": ["./node_modules/os-browserify"],
      "url": ["./node_modules/url"],
      "fs": ["./node_modules/fs-web"]
    },
    "types": []
  },
  "files": [
    "src/main.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

But fails miserably at runtime with the following error:

> src_app_login_login_module_ts.js:1 ERROR Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at 2942 (capability.js:1:28)
    at __webpack_require__ (bootstrap:19:1)
    at 866 (request.js:1:18)
    at __webpack_require__ (bootstrap:19:1)
    at 1376 (index.js:1:21)
    at __webpack_require__ (bootstrap:19:1)
    at 7018 (index.js:1:12)
    at __webpack_require__ (bootstrap:19:1)
    at 9046 (APIMethod.js:32:28)
    at __webpack_require__ (bootstrap:19:1)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24300:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)

 triggering code: 
```js
let userCred: MyInvestorUserData={
      user,
      password,
      device_id: this._myUUId
    };
    const auther = new MyInvestorAuthenticator(userCred);
```

Any help will be really appreciated since idk what can I be doing wrong in  a such clean environment + following readme steps

**Comment by masterfaka** [comment]
atm got it building adding node polyfills as bellow:
- polyfills.ts

`import * as process from "process";
import * as Buffer from "buffer";

(window as any).global = window; ///miai-api pollyfill
(window as any).process = process;
(window as any).Buffer = Buffer;
`
- tsconfig.ts
```js
...
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "paths" : {
      "crypto": ["node_modules/crypto-browserify"],
      "stream": ["node_modules/stream-browserify"],
      "assert": ["node_modules/assert"],
      "http": ["node_modules/stream-http"],
      "https": ["node_modules/https-browserify"],
      "os": ["node_modules/os-browserify"],
      "url": ["node_modules/url"],
      "fs": ["node_modules/fs-web"],
      "process": ["node_modules/process"],
      "buffer": ["node_modules/buffer"]
    },
    "types": [
      "node"
    ]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
...
```
(which by the way will very nicely warn you of some errors in lib that we can ignore with @ts-ignore):
- SavingsAccount.d.ts
```ts
..
export declare class SavingsAccount extends CheckingAccount {
    // @ts-ignore
  iban: undefined;
    // @ts-ignore
  recurring_payments_greater_than_balance: undefined;
...
```

but still fails at runtime with the following error:

> login-api.service.ts:33 Unhandled Promise rejection: Buffer.from is not a function ; Zone: <root> ; Task: null ; Value: TypeError: Buffer.from is not a function
    at response.js:50:34
    at new ZoneAwarePromise (zone.js:1432:21)
    at Object.write (response.js:47:13) TypeError: Buffer.from is not a function
    at http://localhost:4200/src_app_login_login_module_ts.js:37915:41
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:10751:21)
    at Object.write (http://localhost:4200/src_app_login_login_module_ts.js:37912:18)
api.onUnhandledError @ zone.js:1064
handleUnhandledRejection @ zone.js:1089
api.microtaskDrainDone @ zone.js:1083
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
resolvePromise @ zone.js:1230
ZoneAwarePromise @ zone.js:1435
write @ response.js:47
Promise.then (async)
exports.IncomingMessage @ response.js:70
ClientRequest._connect @ request.js:260
(anonymous) @ request.js:153
invoke @ zone.js:375
onInvoke @ core.mjs:24313
invoke @ zone.js:374
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:408
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:408
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Zone - Promise.then (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
resolvePromise @ zone.js:1205
(anonymous) @ zone.js:1121
(anonymous) @ zone.js:1137
Promise.then (async)
(anonymous) @ zone.js:1512
ZoneAwarePromise @ zone.js:1432
Ctor.then @ zone.js:1511
ClientRequest._onFinish @ request.js:150
(anonymous) @ request.js:61
emit @ events.js:153
finishMaybe @ _stream_writable.js:624
afterWrite @ _stream_writable.js:470
Item.run @ browser.js:153
drainQueue @ browser.js:123
timer @ zone.js:2408
invokeTask @ zone.js:409
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:408
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:408
runTask @ zone.js:178
invokeTask @ zone.js:490
ZoneTask.invoke @ zone.js:479
data.args.<computed> @ zone.js:2388
Zone - setTimeout (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:686
(anonymous) @ zone.js:2432
proto.<computed> @ zone.js:976
runTimeout @ browser.js:41
process.nextTick @ browser.js:143
onwrite @ _stream_writable.js:459
WritableState.onwrite @ _stream_writable.js:160
ClientRequest._write @ request.js:272
doWrite @ _stream_writable.js:409
writeOrBuffer @ _stream_writable.js:398
Writable.write @ _stream_writable.js:307
(anonymous) @ APIMethod.js:139
(anonymous) @ APIMethod.js:27
ZoneAwarePromise @ zone.js:1432
push.9046.__awaiter @ APIMethod.js:23
_request @ APIMethod.js:96
(anonymous) @ RequestToken.js:29
(anonymous) @ RequestToken.js:8
ZoneAwarePromise @ zone.js:1432
push.4587.__awaiter @ RequestToken.js:4
request @ RequestToken.js:22
(anonymous) @ API.js:22
(anonymous) @ API.js:8
ZoneAwarePromise @ zone.js:1432
push.8011.__awaiter @ API.js:4
requestToken @ API.js:22
(anonymous) @ Authenticator.js:18
(anonymous) @ Authenticator.js:8
ZoneAwarePromise @ zone.js:1432
push.9394.__awaiter @ Authenticator.js:4
getToken @ Authenticator.js:17
(anonymous) @ login-api.service.ts:33
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
ZoneAwarePromise @ zone.js:1432
(anonymous) @ asyncToGenerator.js:19
attemptLogin @ login-api.service.ts:47
loginApi @ login-api.service.ts:19
submit @ login.component.ts:21
LoginComponent_Template_button_click_9_listener @ login.component.html:11
executeListenerWithErrorHandling @ core.mjs:14090
wrapListenerIn_markDirtyAndPreventDefault @ core.mjs:14123
(anonymous) @ platform-browser.mjs:402
invokeTask @ zone.js:409
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:408
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:408
runTask @ zone.js:178
invokeTask @ zone.js:490
invokeTask @ zone.js:1664
globalCallback @ zone.js:1695
globalZoneAwareCallback @ zone.js:1728
Zone - HTMLButtonElement.addEventListener:click (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleEventTask @ zone.js:247
(anonymous) @ zone.js:1967
addEventListener @ platform-browser.mjs:657
addEventListener @ platform-browser.mjs:232
listen @ platform-browser.mjs:581
listen @ animations.mjs:299
listenerInternal @ core.mjs:14052
ɵɵlistener @ core.mjs:13933
LoginComponent_Template @ login.component.html:11
executeTemplate @ core.mjs:10534
renderView @ core.mjs:10356
renderComponent @ core.mjs:11529
renderChildComponents @ core.mjs:10216
renderView @ core.mjs:10381
create @ core.mjs:12273
createComponent @ core.mjs:21416
activateWith @ router.mjs:2611
activateRoutes @ router.mjs:3023
(anonymous) @ router.mjs:2972
activateChildRoutes @ router.mjs:2971
activateRoutes @ router.mjs:3030
(anonymous) @ router.mjs:2972
activateChildRoutes @ router.mjs:2971
activate @ router.mjs:2885
(anonymous) @ router.mjs:2870
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.isUnsub @ tap.js:18
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerSubscriber @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerSubscriber @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ take.js:12
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ defaultIfEmpty.js:11
OperatorSubscriber._complete @ OperatorSubscriber.js:36
complete @ Subscriber.js:49
(anonymous) @ innerFrom.js:53
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ defaultIfEmpty.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ take.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerSubscriber @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.isUnsub @ tap.js:18
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerSubscriber @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.isUnsub @ tap.js:18
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerComplete @ mergeInternals.js:25
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
subscribe.innerComplete @ mergeInternals.js:25
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
doInnerSub @ mergeInternals.js:19
outerNext @ mergeInternals.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.buffer @ takeLast.js:14
OperatorSubscriber._complete @ OperatorSubscriber.js:36
complete @ Subscriber.js:49
source.subscribe.isUnsub @ tap.js:23
OperatorSubscriber._complete @ OperatorSubscriber.js:36
complete @ Subscriber.js:49
checkComplete @ mergeInternals.js:11
(anonymous) @ mergeInternals.js:52
OperatorSubscriber._complete @ OperatorSubscriber.js:36
complete @ Subscriber.js:49
(anonymous) @ innerFrom.js:53
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ takeLast.js:9
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
doInnerSub @ mergeInternals.js:19
outerNext @ mergeInternals.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.isUnsub @ tap.js:18
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
Zone - Promise.then (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
then @ zone.js:1464
(anonymous) @ innerFrom.js:59
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
source.subscribe.isUnsub @ tap.js:18
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ filter.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ finalize.js:5
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ catchError.js:9
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ map.js:7
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ filter.js:6
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
next @ BehaviorSubject.js:24
handleNavigationRequest @ router.mjs:4365
scheduleNavigation @ router.mjs:5439
navigateByUrl @ router.mjs:5320
onClick @ router.mjs:5772
RouterLink_click_HostBindingHandler @ router.mjs:5827
executeListenerWithErrorHandling @ core.mjs:14090
wrapListenerIn_markDirtyAndPreventDefault @ core.mjs:14123
(anonymous) @ platform-browser.mjs:402
invokeTask @ zone.js:409
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:408
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:408
runTask @ zone.js:178
invokeTask @ zone.js:490
invokeTask @ zone.js:1664
globalCallback @ zone.js:1695
globalZoneAwareCallback @ zone.js:1728
Zone - HTMLButtonElement.addEventListener:click (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleEventTask @ zone.js:247
(anonymous) @ zone.js:1967
addEventListener @ platform-browser.mjs:657
addEventListener @ platform-browser.mjs:232
listen @ platform-browser.mjs:581
listen @ animations.mjs:299
listenerInternal @ core.mjs:14052
ɵɵlistener @ core.mjs:13933
RouterLink_HostBindings @ router.mjs:443
invokeHostBindingsInCreationMode @ core.mjs:11132
invokeDirectivesHostBindings @ core.mjs:11115
createDirectivesInstances @ core.mjs:10565
ɵɵelementStart @ core.mjs:13716
AppComponent_Template @ app.component.html:128
executeTemplate @ core.mjs:10534
renderView @ core.mjs:10356
renderComponent @ core.mjs:11529
renderChildComponents @ core.mjs:10216
renderView @ core.mjs:10381
create @ core.mjs:12273
bootstrap @ core.mjs:25368
(anonymous) @ core.mjs:25028
_moduleDoBootstrap @ core.mjs:25028
(anonymous) @ core.mjs:24998
invoke @ zone.js:375
onInvoke @ core.mjs:24313
invoke @ zone.js:374
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:408
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:408
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Zone - Promise.then (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:389
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
then @ zone.js:1464
(anonymous) @ core.mjs:24994
_callAndReportToErrorHandler @ core.mjs:25106
(anonymous) @ core.mjs:24991
invoke @ zone.js:375
onInvoke @ core.mjs:24313
invoke @ zone.js:374
run @ zone.js:134
run @ core.mjs:24167
bootstrapModuleFactory @ core.mjs:24973
(anonymous) @ core.mjs:25023
invoke @ zone.js:375
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
scheduleTask @ zone.js:399
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
then @ zone.js:1464
bootstrapModule @ core.mjs:25023
4431 @ main.ts:6
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:7
(anonymous) @ main.ts:7
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:7
webpackJsonpCallback @ jsonp chunk loading:71
(anonymous) @ main.js:2
Show 558 more frames
login-api.service.ts:33 ERROR Error: Uncaught (in promise): TypeError: Buffer.from is not a function
TypeError: Buffer.from is not a function
    at response.js:50:34
    at new ZoneAwarePromise (zone.js:1432:21)
    at Object.write (response.js:47:13)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24300:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)

**Comment by masterfaka** [comment]
Reinstalling all node modules and providing correct polyfills made it work.

- polyfills.ts

```ts

import * as process from "process";
//import * as Buffer from "buffer/";
import { Buffer } from 'buffer';

(window as any).global = window; ///miai-api pollyfill
(window as any).process = process;
(window as any).Buffer = Buffer;

```

- tsconfig.json

```js

/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "paths" : {
      "crypto": ["node_modules/crypto-browserify"],
      "stream": ["node_modules/stream-browserify"],
      "assert": ["node_modules/assert"],
      "http": ["node_modules/stream-http"],
      "https": ["node_modules/https-browserify"],
      "os": ["node_modules/os-browserify"],
      "url": ["node_modules/url"],
      "fs": ["node_modules/fs-web"],
      "process": ["node_modules/process"],
      "buffer": ["node_modules/buffer"]
    },
    "types": [
      "node"
    ]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}

```

- angular.json 

```ts

...
architect :{
 ...
   build:{
    ....
    options:{
             "allowedCommonJsDependencies": [
              "crypto","stream","assert","http","https", "os","url","fs", "process", "buffer"
            ],
            "polyfills": [
              "zone.js",
              "src/polyfills.ts"
            ],
           ...
.......
}
```

**Comment by joaquinrovira** [comment]
Hello, I am currently unavailable to work on the project and has been mostly abandoned. Thank you for showing interest though!

I am still planning on developing a fully automated investment tool for MyInvestor following MSCI indexes and index funds. Due to the lack of time I don't think it will happen any time soon.

**Comment by xivira** [comment]
Hello, I am currently unavailable to work on the project and it has been mostly abandoned. Thank you for showing interest though!

I am still planning on developing a fully automated investment tool for MyInvestor following [MSCI reports](https://www.msci.com/our-solutions/indexes) and [available index funds](https://myinvestor.es/inversion/fondos-inversion). Due to the lack of time I don't think it will happen any time soon.
